### ISSUE TITLE
Issue compiling aescrypt 4.1.1

### ISSUE THREAD

**Issue by edsilegxrepo** [terrapane/aescrypt_cli#2]

**Comment by CodeCracker-oss** [comment]
I face this issue as well, tag 4.1.0 and 4.1.1 fail to build due to failure downloading aescrypt_lm dependency from its github page.

There is no aescrypt_lm repository available, and therefore yields github Error 404 page.

Any plans addressing this @paulej ?

**Comment by edsilegxrepo** [comment]
I feel that the increasingly closed direction of the product recently will be detrimental long term. It used to be a great solution.

**Comment by paulej** [comment]
@CodeCracker-oss, this library is the licensing module, which is not published. I have considered providing a simple build option to just disable it for those that want to build AES Crypt from the source code. This came about because people actually demanded a license key and so a mechanism was introduced to make that possible.

@mshedsilegx, we fully intend to continue publishing the source code.  However, we need to strike a balance between offering a product we can sell and support, while also making the source available so people have a chance to review it and feel assured there are no back doors, etc. BTW, sorry I did not see your message before. I got notified when I was explicitly tagged, but did not see the original issue when raised.

**Comment by CodeCracker-oss** [comment]
I could disable it myself I suppose, but if you could implement a function to disable it more easily that would be nice for myself and others.

And I understand the concept of wanting support from it, when I first came back to aescrypt on its homepage, it looked like it went commercial and most commercial software is proprietary. That was my concern until I realized it was still open source.

When it comes to cryptography, open source is required to ensure good security and trust in the community, so I am glad to see it still remains open.

**Comment by edsilegxrepo** [comment]
@paulej  I totally understand from your point of view. Unfortunately, due to the license shift for its usage, we are going to switch to another solution. It is a high quality tool, well supported, and I regret that decision. Thanks again for making this available for many years to the community.

**Comment by paulej** [comment]
@CodeCracker-oss, I don't use the term "open source", as it has certain meaning that people take exception to with how AES Crypt is published. It is commercial software, but fully published source code (except for that license module that is giving you trouble).  I'll make a change to master to allow bypassing it with `aescrypt_DISABLE_LICENSE_MODULE` or something. With that option turned on, it should be possible to build without that repository. All of the functionality is otherwise be the same, just skipping over the license check.

@mshedsilegx, I'm the original author and long-time maintainer of the software, and Terrapane remains committed to continuing to publish the source code indefinitely. I personally spent a lot of time creating this entirely new version of AES Crypt, improving the performance and security of the software. It's unfortunate that a small, one-time license fee would cause such a negative reaction.

**Comment by paulej** [comment]
@CodeCracker-oss, I just pushed a commit to master that allows building the command-line code without the license module.  There is documentation in the README, but this is the way to build the enterprise build that will not perform license checks:

```bash
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Daescrypt_ENABLE_LICENSE_MODULE:BOOL=OFF
cmake --build build --parallel
```

**Comment by CodeCracker-oss** [comment]
@paulej Thank you for quickly addressing this issue, I can confirm it builds successfully now.
